"""
Prometheus metrics definitions and setup.

Registers custom metrics that are domain-specific to the PA Review Platform.
The prometheus-fastapi-instrumentator library handles generic HTTP metrics
(request count, latency histogram, in-progress gauge).

Custom metrics tracked here:
- OCR confidence scores
- LLM call latency and token usage
- Prior authorization decision distribution (approve/deny/pend)
- Clarification loop counts
- Policy retrieval latency
- Reviewer override rate
- Queue backlog size

Usage in service code:
    from app.monitoring.metrics import METRICS
    METRICS.ocr_confidence.observe(0.95)
    METRICS.pa_decisions_total.labels(decision="APPROVE").inc()
"""

from __future__ import annotations

import structlog
from fastapi import FastAPI
from prometheus_client import Counter, Gauge, Histogram, Summary
from prometheus_fastapi_instrumentator import Instrumentator

logger = structlog.get_logger(__name__)

# ----------------------------------------------------------
# Metric definitions
# ----------------------------------------------------------

# OCR
OCR_CONFIDENCE = Histogram(
    name="pa_ocr_confidence_score",
    documentation="OCR extraction confidence score (0.0–1.0)",
    labelnames=["provider"],  # azure | paddleocr
    buckets=[0.5, 0.6, 0.7, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99, 1.0],
)

OCR_REQUESTS_TOTAL = Counter(
    name="pa_ocr_requests_total",
    documentation="Total OCR requests by provider and outcome",
    labelnames=["provider", "outcome"],  # outcome: success | fallback | failure
)

# LLM
LLM_LATENCY_SECONDS = Histogram(
    name="pa_llm_latency_seconds",
    documentation="LLM API call latency in seconds",
    labelnames=["operation"],  # extraction | reasoning | clarification
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0],
)

LLM_TOKENS_TOTAL = Counter(
    name="pa_llm_tokens_total",
    documentation="Total LLM tokens consumed",
    labelnames=["operation", "token_type"],  # token_type: prompt | completion
)

LLM_ERRORS_TOTAL = Counter(
    name="pa_llm_errors_total",
    documentation="LLM API errors by type",
    labelnames=["error_type"],  # timeout | rate_limit | api_error
)

# Prior Authorization Decisions
PA_DECISIONS_TOTAL = Counter(
    name="pa_decisions_total",
    documentation="Prior authorization decisions by outcome",
    labelnames=["decision", "decision_source"],  # decision: APPROVE|DENY|PEND, source: ai|reviewer_override
)

# Clarification Loops
CLARIFICATION_LOOPS_TOTAL = Counter(
    name="pa_clarification_loops_total",
    documentation="Clarification loop iterations by outcome",
    labelnames=["outcome"],  # resolved | escalated | max_exceeded
)

CLARIFICATION_ATTEMPTS = Histogram(
    name="pa_clarification_attempts",
    documentation="Number of clarification attempts per case",
    buckets=[1, 2, 3],
)

CLARIFICATION_QUESTION_GENERATED_TOTAL = Counter(
    name="pa_clarification_question_generated_total",
    documentation="Clarification questions generated by method and clinical category",
    labelnames=["generated_by", "category"],  # generated_by: llm | template
)

CLARIFICATION_RESPONSE_QUALITY_TOTAL = Counter(
    name="pa_clarification_response_quality_total",
    documentation="Provider response quality assessments by quality level",
    labelnames=["quality"],  # sufficient | partial | insufficient | unrelated
)

CLARIFICATION_ESCALATIONS_TOTAL = Counter(
    name="pa_clarification_escalations_total",
    documentation="Clarification escalations to human review by reason",
    labelnames=["reason"],  # max_attempts_reached | timeout | insufficient_response | repeated_same_question | clinical_complexity | policy_ambiguity
)

CLARIFICATION_NOTIFICATIONS_TOTAL = Counter(
    name="pa_clarification_notifications_total",
    documentation="Reviewer notification events dispatched by event type",
    labelnames=["event"],  # clarification_sent | clarification_answered | clarification_timeout | max_attempts_reached | escalated_to_reviewer
)

CLARIFICATION_RESPONSE_LATENCY_HOURS = Histogram(
    name="pa_clarification_response_latency_hours",
    documentation="Time between clarification question sent and provider response (hours)",
    buckets=[1, 4, 8, 12, 24, 48, 72, 120],
)

CLARIFICATION_MISSING_ITEMS_COUNT = Histogram(
    name="pa_clarification_missing_items_count",
    documentation="Number of missing information items detected per clarification cycle",
    buckets=[1, 2, 3, 5, 8, 12, 20],
)

# Policy Retrieval
RETRIEVAL_LATENCY_SECONDS = Histogram(
    name="pa_retrieval_latency_seconds",
    documentation="Pinecone policy retrieval latency in seconds",
    labelnames=["retrieval_type"],  # semantic | hybrid
    buckets=[0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0],
)

RETRIEVAL_RESULTS_COUNT = Histogram(
    name="pa_retrieval_results_count",
    documentation="Number of policy chunks returned per retrieval",
    buckets=[0, 1, 2, 3, 5, 10, 20],
)

# Human Review
REVIEWER_OVERRIDES_TOTAL = Counter(
    name="pa_reviewer_overrides_total",
    documentation="Number of times reviewers overrode AI recommendations",
    labelnames=["original_ai_decision", "reviewer_decision"],
)

REVIEWER_LATENCY_SECONDS = Histogram(
    name="pa_reviewer_latency_seconds",
    documentation="Time between case assignment and reviewer decision",
    buckets=[60, 300, 900, 1800, 3600, 7200, 86400],
)

# Queue
QUEUE_BACKLOG = Gauge(
    name="pa_queue_backlog_size",
    documentation="Number of unprocessed PA requests in the message queue",
    labelnames=["queue_name"],
)

# Cases
PA_CASES_ACTIVE = Gauge(
    name="pa_cases_active",
    documentation="Number of PA cases currently in progress",
)

PA_CASE_PROCESSING_SECONDS = Histogram(
    name="pa_case_processing_seconds",
    documentation="End-to-end PA case processing time in seconds",
    buckets=[30, 60, 120, 300, 600, 1200, 1800, 3600],
)


# Cache
CACHE_HITS_TOTAL = Counter(
    name="pa_cache_hits_total",
    documentation="Cache hits by domain",
    labelnames=["domain"],  # retrieval | llm | embedding | session | clarification
)

CACHE_MISSES_TOTAL = Counter(
    name="pa_cache_misses_total",
    documentation="Cache misses by domain",
    labelnames=["domain"],
)

CACHE_ERRORS_TOTAL = Counter(
    name="pa_cache_errors_total",
    documentation="Cache operation errors by domain and operation type",
    labelnames=["domain", "operation"],  # operation: get | set | delete | pattern_delete
)

CACHE_SET_SIZE_BYTES = Summary(
    name="pa_cache_set_size_bytes",
    documentation="Approximate size of values written to cache (serialized bytes)",
    labelnames=["domain"],
)


# OCR Fallback
OCR_FALLBACK_TOTAL = Counter(
    name="pa_ocr_fallback_total",
    documentation="OCR fallback events by reason and provider transition",
    labelnames=["reason", "from_provider", "to_provider"],
)

OCR_PROCESSING_SECONDS = Histogram(
    name="pa_ocr_processing_seconds",
    documentation="OCR extraction latency per provider and document type",
    labelnames=["provider", "document_type"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0],
)

OCR_PAGES_TOTAL = Counter(
    name="pa_ocr_pages_total",
    documentation="Total pages processed by each OCR provider",
    labelnames=["provider"],
)

# Document Ingestion
DOCUMENT_INGESTION_TOTAL = Counter(
    name="pa_document_ingestion_total",
    documentation="Total documents ingested by type and status",
    labelnames=["document_type", "status"],
)

DOCUMENT_INGESTION_SECONDS = Histogram(
    name="pa_document_ingestion_seconds",
    documentation="End-to-end document ingestion latency by document type",
    labelnames=["document_type"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0],
)

DOCUMENT_CONFIDENCE_SCORE = Histogram(
    name="pa_document_confidence_score",
    documentation="Final document confidence score after OCR/normalization",
    labelnames=["document_type", "ocr_provider"],
    buckets=[0.5, 0.6, 0.7, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99, 1.0],
)

# Workflow
PA_RECOMMENDATIONS_TOTAL = Counter(
    name="pa_recommendations_total",
    documentation="PA recommendations by type (approve | deny | pend_for_info | refer_medical_director)",
    labelnames=["recommendation_type"],
)

WORKFLOW_LATENCY_SECONDS = Histogram(
    name="pa_workflow_latency_seconds",
    documentation="End-to-end workflow execution time in seconds",
    buckets=[30, 60, 120, 300, 600, 1200, 1800, 3600],
)

WORKFLOW_INTERRUPTS_TOTAL = Counter(
    name="pa_workflow_interrupts_total",
    documentation="Workflow interrupt events by type",
    labelnames=["interrupt_type"],  # clarification_required | human_review_required
)


# Hybrid Retrieval Orchestrator
RETRIEVAL_STRATEGY_LATENCY_SECONDS = Histogram(
    name="pa_retrieval_strategy_latency_seconds",
    documentation="Per-strategy retrieval latency in the hybrid orchestrator",
    labelnames=["strategy"],  # semantic | hybrid | cpt | icd
    buckets=[0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0],
)

RETRIEVAL_FUSION_CANDIDATES = Histogram(
    name="pa_retrieval_fusion_candidates",
    documentation="Number of candidate chunks entering RRF fusion",
    buckets=[5, 10, 20, 50, 100, 200],
)

RETRIEVAL_PRECISION_AT_K = Histogram(
    name="pa_retrieval_precision_at_k",
    documentation="Proxy Precision@K for the hybrid retrieval pipeline (k=5)",
    buckets=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
)

RETRIEVAL_NDCG_AT_K = Histogram(
    name="pa_retrieval_ndcg_at_k",
    documentation="Proxy NDCG@K for the hybrid retrieval pipeline (k=5)",
    buckets=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
)

RERANKER_LATENCY_SECONDS = Histogram(
    name="pa_reranker_latency_seconds",
    documentation="Reranker (Cohere or fallback) call latency",
    labelnames=["reranker_type"],  # cohere | score_fusion
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 5.0],
)

CPT_EXPANSION_SIZE = Histogram(
    name="pa_cpt_expansion_size",
    documentation="Number of CPT codes after hierarchy expansion",
    buckets=[1, 2, 3, 5, 10, 15, 20],
)

ICD_EXPANSION_SIZE = Histogram(
    name="pa_icd_expansion_size",
    documentation="Number of ICD codes after hierarchy expansion",
    buckets=[1, 2, 3, 5, 10, 15, 25],
)


# AI Reasoning Engine — Guardrails + Multi-Model Orchestration
GUARDRAIL_VIOLATIONS_TOTAL = Counter(
    name="pa_guardrail_violations_total",
    documentation="Guardrail violations by type and severity",
    labelnames=["violation_type", "severity"],
)

GUARDRAIL_PASS_RATE = Counter(
    name="pa_guardrail_outcomes_total",
    documentation="Guardrail pipeline pass/fail outcomes",
    labelnames=["result"],  # pass | fail
)

REASONING_ESCALATIONS_TOTAL = Counter(
    name="pa_reasoning_escalations_total",
    documentation="Model escalation events by trigger and source tier",
    labelnames=["trigger", "from_tier"],
)

REASONING_ATTEMPTS_TOTAL = Counter(
    name="pa_reasoning_attempts_total",
    documentation="LLM reasoning attempts by tier and outcome",
    labelnames=["tier", "outcome"],  # outcome: success | failure
)

REASONING_HUMAN_ESCALATIONS_TOTAL = Counter(
    name="pa_reasoning_human_escalations_total",
    documentation="Cases escalated to human review from the reasoning engine",
    labelnames=["reason"],  # repeated_violations | unsafe_output | max_attempts | input_invalid
)

REASONING_GUARDRAIL_VIOLATIONS_TOTAL = Counter(
    name="pa_reasoning_guardrail_violations_total",
    documentation="Per-violation-type count from the reasoning guardrail pipeline",
    labelnames=["violation_type"],
)

REASONING_LATENCY_SECONDS = Histogram(
    name="pa_reasoning_latency_seconds",
    documentation="End-to-end reasoning pipeline latency per policy evaluation",
    labelnames=["tier"],  # small | medium | large
    buckets=[1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 60.0, 120.0],
)

REASONING_CONFIDENCE_SCORE = Histogram(
    name="pa_reasoning_confidence_score",
    documentation="Overall confidence score from the reasoning engine",
    buckets=[0.3, 0.4, 0.5, 0.6, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.0],
)


# API Route metrics
PA_REQUESTS_SUBMITTED_TOTAL = Counter(
    name="pa_requests_submitted_total",
    documentation="PA requests submitted via API by service type, priority, and channel",
    labelnames=["service_type", "priority", "channel"],
)

CASE_VIEWS_TOTAL = Counter(
    name="pa_case_views_total",
    documentation="Case detail views by case status",
    labelnames=["status"],
)

DOCUMENTS_UPLOADED_TOTAL = Counter(
    name="pa_documents_uploaded_total",
    documentation="Documents uploaded by document type and content type",
    labelnames=["document_type", "content_type"],
)

DOCUMENT_SIZE_BYTES = Histogram(
    name="pa_document_size_bytes",
    documentation="Uploaded document size in bytes by document type",
    labelnames=["document_type"],
    buckets=[1024, 10240, 102400, 512000, 1048576, 5242880, 10485760, 26214400],
)

DOCUMENT_DOWNLOADS_TOTAL = Counter(
    name="pa_document_downloads_total",
    documentation="Document downloads by document type",
    labelnames=["document_type"],
)

REVIEW_DECISIONS_TOTAL = Counter(
    name="pa_review_decisions_total",
    documentation="Human reviewer decisions by outcome and decision source",
    labelnames=["outcome", "source"],
)

REVIEW_ESCALATIONS_TOTAL = Counter(
    name="pa_review_escalations_total",
    documentation="Manual escalations by whether a target reviewer was specified",
    labelnames=["has_target"],
)

CLARIFICATION_EXHAUSTED_TOTAL = Counter(
    name="pa_clarification_exhausted_total",
    documentation="Cases auto-escalated after exhausting maximum clarification attempts",
)

CLARIFICATION_RESPONSES_TOTAL = Counter(
    name="pa_clarification_responses_total",
    documentation="Clarification responses submitted, labelled by resulting case status",
    labelnames=["case_status"],
)


class PAMetrics:
    """
    Convenience wrapper giving attribute-style access to all metrics.

    Import this singleton:
        from app.monitoring.metrics import METRICS
        METRICS.ocr_confidence.observe(score, labels=["azure"])
    """

    def __init__(self) -> None:
        self.ocr_confidence = OCR_CONFIDENCE
        self.ocr_requests_total = OCR_REQUESTS_TOTAL
        self.llm_latency_seconds = LLM_LATENCY_SECONDS
        self.llm_tokens_total = LLM_TOKENS_TOTAL
        self.llm_errors_total = LLM_ERRORS_TOTAL
        self.pa_decisions_total = PA_DECISIONS_TOTAL
        self.clarification_loops_total = CLARIFICATION_LOOPS_TOTAL
        self.clarification_attempts = CLARIFICATION_ATTEMPTS
        self.clarification_question_generated_total = CLARIFICATION_QUESTION_GENERATED_TOTAL
        self.clarification_response_quality_total = CLARIFICATION_RESPONSE_QUALITY_TOTAL
        self.clarification_escalations_total = CLARIFICATION_ESCALATIONS_TOTAL
        self.clarification_notifications_total = CLARIFICATION_NOTIFICATIONS_TOTAL
        self.clarification_response_latency_hours = CLARIFICATION_RESPONSE_LATENCY_HOURS
        self.clarification_missing_items_count = CLARIFICATION_MISSING_ITEMS_COUNT
        self.retrieval_latency_seconds = RETRIEVAL_LATENCY_SECONDS
        self.retrieval_results_count = RETRIEVAL_RESULTS_COUNT
        self.reviewer_overrides_total = REVIEWER_OVERRIDES_TOTAL
        self.reviewer_latency_seconds = REVIEWER_LATENCY_SECONDS
        self.queue_backlog = QUEUE_BACKLOG
        self.pa_cases_active = PA_CASES_ACTIVE
        self.pa_case_processing_seconds = PA_CASE_PROCESSING_SECONDS
        self.cache_hits_total = CACHE_HITS_TOTAL
        self.cache_misses_total = CACHE_MISSES_TOTAL
        self.cache_errors_total = CACHE_ERRORS_TOTAL
        self.cache_set_size_bytes = CACHE_SET_SIZE_BYTES
        # OCR + Document ingestion
        self.ocr_fallback_total = OCR_FALLBACK_TOTAL
        self.ocr_processing_seconds = OCR_PROCESSING_SECONDS
        self.ocr_pages_total = OCR_PAGES_TOTAL
        self.document_ingestion_total = DOCUMENT_INGESTION_TOTAL
        self.document_ingestion_seconds = DOCUMENT_INGESTION_SECONDS
        self.document_confidence_score = DOCUMENT_CONFIDENCE_SCORE
        # Workflow
        self.pa_recommendations_total = PA_RECOMMENDATIONS_TOTAL
        self.workflow_latency_seconds = WORKFLOW_LATENCY_SECONDS
        self.workflow_interrupts_total = WORKFLOW_INTERRUPTS_TOTAL
        # Guardrails + reasoning engine
        self.guardrail_violations_total = GUARDRAIL_VIOLATIONS_TOTAL
        self.guardrail_pass_rate = GUARDRAIL_PASS_RATE
        self.reasoning_escalations_total = REASONING_ESCALATIONS_TOTAL
        self.reasoning_attempts_total = REASONING_ATTEMPTS_TOTAL
        self.reasoning_human_escalations_total = REASONING_HUMAN_ESCALATIONS_TOTAL
        self.reasoning_guardrail_violations_total = REASONING_GUARDRAIL_VIOLATIONS_TOTAL
        self.reasoning_latency_seconds = REASONING_LATENCY_SECONDS
        self.reasoning_confidence_score = REASONING_CONFIDENCE_SCORE
        # Hybrid retrieval orchestrator
        self.retrieval_strategy_latency_seconds = RETRIEVAL_STRATEGY_LATENCY_SECONDS
        self.retrieval_fusion_candidates = RETRIEVAL_FUSION_CANDIDATES
        self.retrieval_precision_at_k = RETRIEVAL_PRECISION_AT_K
        self.retrieval_ndcg_at_k = RETRIEVAL_NDCG_AT_K
        self.reranker_latency_seconds = RERANKER_LATENCY_SECONDS
        self.cpt_expansion_size = CPT_EXPANSION_SIZE
        self.icd_expansion_size = ICD_EXPANSION_SIZE
        # API route metrics
        self.pa_requests_submitted_total = PA_REQUESTS_SUBMITTED_TOTAL
        self.case_views_total = CASE_VIEWS_TOTAL
        self.documents_uploaded_total = DOCUMENTS_UPLOADED_TOTAL
        self.document_size_bytes = DOCUMENT_SIZE_BYTES
        self.document_downloads_total = DOCUMENT_DOWNLOADS_TOTAL
        self.review_decisions_total = REVIEW_DECISIONS_TOTAL
        self.review_escalations_total = REVIEW_ESCALATIONS_TOTAL
        self.clarification_exhausted_total = CLARIFICATION_EXHAUSTED_TOTAL
        self.clarification_responses_total = CLARIFICATION_RESPONSES_TOTAL


# Module-level singleton
METRICS = PAMetrics()


def setup_metrics(app: FastAPI) -> None:
    """
    Register Prometheus metrics with the FastAPI application.

    Called once during application startup.
    Instruments generic HTTP metrics automatically and exposes /metrics endpoint.
    """
    settings_module = __import__("app.core.config.settings", fromlist=["get_settings"])
    settings = settings_module.get_settings()

    if not settings.prometheus_enabled:
        logger.info("metrics.prometheus_disabled")
        return

    Instrumentator(
        # Exclude health/readiness probes from HTTP metrics
        excluded_handlers=["/api/v1/health", "/api/v1/health/live", "/api/v1/health/ready"],
        # Include response body size in metrics
        body_handlers=[],
        # Group status codes (2xx, 4xx, 5xx) to reduce cardinality
        group_status_codes=False,
    ).instrument(app).expose(
        app,
        endpoint=settings.prometheus_endpoint,
        include_in_schema=False,
        tags=["Monitoring"],
    )

    logger.info(
        "metrics.prometheus_initialized",
        endpoint=settings.prometheus_endpoint,
    )
