import { useState } from 'react'
import { formatDistanceToNow, format } from 'date-fns'
import { clsx } from 'clsx'
import { MessageCircle, Send, Clock, CheckCircle2, XCircle, ArrowUpCircle } from 'lucide-react'
import type { ClarificationRequest, ClarificationStatus } from '@/api/types'
import { useRespondToClarification } from '@/hooks/useReview'

interface ClarificationResponsesProps {
  caseId: string
  clarifications: ClarificationRequest[]
}

const STATUS_CONFIG: Record<ClarificationStatus, { label: string; icon: React.ReactNode; color: string }> = {
  PENDING:   { label: 'Awaiting Response', icon: <Clock className="w-3.5 h-3.5" />,        color: 'text-amber-600 bg-amber-50 border-amber-200' },
  ANSWERED:  { label: 'Response Received', icon: <CheckCircle2 className="w-3.5 h-3.5" />, color: 'text-green-600 bg-green-50 border-green-200' },
  TIMEOUT:   { label: 'Expired',           icon: <XCircle className="w-3.5 h-3.5" />,      color: 'text-slate-500 bg-slate-50 border-slate-200' },
  ESCALATED: { label: 'Escalated',         icon: <ArrowUpCircle className="w-3.5 h-3.5" />, color: 'text-purple-600 bg-purple-50 border-purple-200' },
}

export function ClarificationResponses({ caseId, clarifications }: ClarificationResponsesProps) {
  const [activeId, setActiveId] = useState<string | null>(null)

  if (clarifications.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-24 text-slate-400 text-sm gap-2">
        <MessageCircle className="w-6 h-6 opacity-40" />
        No clarification requests
      </div>
    )
  }

  return (
    <div className="space-y-3">
      {clarifications.map((cl) => (
        <ClarificationCard
          key={cl.clarification_id}
          caseId={caseId}
          clarification={cl}
          isResponding={activeId === cl.clarification_id}
          onToggleRespond={() => setActiveId((prev) =>
            prev === cl.clarification_id ? null : cl.clarification_id,
          )}
        />
      ))}
    </div>
  )
}

function ClarificationCard({
  caseId, clarification: cl, isResponding, onToggleRespond,
}: {
  caseId: string
  clarification: ClarificationRequest
  isResponding: boolean
  onToggleRespond: () => void
}) {
  const [response, setResponse]  = useState('')
  const { mutate, isPending }    = useRespondToClarification()
  const statusCfg                = STATUS_CONFIG[cl.status]
  const canRespond               = cl.status === 'PENDING'

  const handleSubmit = () => {
    mutate(
      { caseId, clarificationId: cl.clarification_id, response },
      { onSuccess: () => { setResponse(''); onToggleRespond() } },
    )
  }

  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden">
      {/* Header */}
      <div className="p-3 bg-slate-50">
        <div className="flex items-start justify-between gap-2 mb-2">
          <span className={clsx(
            'inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded border',
            statusCfg.color,
          )}>
            {statusCfg.icon}
            {statusCfg.label}
          </span>
          <span className="text-xs text-slate-400 flex-shrink-0">
            {formatDistanceToNow(new Date(cl.sent_at), { addSuffix: true })}
          </span>
        </div>

        <p className="text-sm font-medium text-slate-800 leading-snug mb-1">{cl.question}</p>

        <p className="text-xs text-slate-500">
          Generated by <span className="font-medium text-slate-700 capitalize">{cl.generated_by}</span>
          {cl.attempt_number > 1 && (
            <span className="ml-2 text-amber-600">· Attempt #{cl.attempt_number}</span>
          )}
        </p>
      </div>

      {/* Provider response */}
      {cl.response && (
        <div className="px-3 py-2.5 bg-white border-t border-slate-100">
          <p className="text-xs font-semibold text-slate-500 mb-1">Provider Response</p>
          <p className="text-sm text-slate-700 leading-relaxed">{cl.response}</p>
          {cl.answered_at && (
            <p className="text-xs text-slate-400 mt-1">
              {format(new Date(cl.answered_at), 'MMM d, yyyy · h:mm a')}
            </p>
          )}
        </div>
      )}

      {/* Reviewer reply form */}
      {canRespond && (
        <div className="border-t border-slate-100">
          {isResponding ? (
            <div className="p-3 space-y-2">
              <textarea
                value={response}
                onChange={(e) => setResponse(e.target.value)}
                rows={3}
                placeholder="Enter your follow-up or response…"
                className="w-full text-sm border border-slate-200 rounded-lg p-2 resize-none focus:outline-none focus:ring-2 focus:ring-brand-400 placeholder-slate-300"
                autoFocus
              />
              <div className="flex gap-2 justify-end">
                <button
                  onClick={onToggleRespond}
                  className="text-xs text-slate-500 hover:text-slate-700 px-3 py-1.5"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={response.trim().length < 3 || isPending}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-brand-600 text-white rounded-lg hover:bg-brand-700 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Send className="w-3 h-3" />
                  {isPending ? 'Sending…' : 'Send Response'}
                </button>
              </div>
            </div>
          ) : (
            <button
              onClick={onToggleRespond}
              className="w-full flex items-center gap-2 px-3 py-2 text-xs text-brand-600 hover:bg-brand-50 transition-colors"
            >
              <Send className="w-3.5 h-3.5" />
              Reply to clarification
            </button>
          )}
        </div>
      )}
    </div>
  )
}
