import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Brain, ChevronDown, ChevronUp, Lightbulb, AlertTriangle, BookOpen, Cpu } from 'lucide-react'
import { ConfidenceBar } from '@/components/common/ConfidenceBar'

const RATIONALE = {
  recommendation: 'APPROVE',
  confidence: 0.91,
  summary: 'Based on comprehensive analysis of submitted clinical documentation, patient Maria Gonzalez meets all primary eligibility criteria for total knee arthroplasty (CPT 27447). The case demonstrates clear medical necessity through documented failure of conservative management, radiographic evidence of severe disease, and significant functional impairment.',
  model: 'gpt-4o',
  tier: 'LARGE',
  reasoning_steps: [
    {
      step: 'Document Analysis',
      content: 'Processed 4 clinical documents (8 pages total). OCR confidence: 98.2%. Extracted 8 clinical entities including confirmed diagnosis codes M17.11 and M25.361.',
    },
    {
      step: 'Policy Retrieval',
      content: 'Retrieved 5 relevant policy sections from payer knowledge base using hybrid dense+sparse retrieval (RRF fusion). Top match: "TKA Medical Necessity Criteria" (similarity: 0.94).',
    },
    {
      step: 'Criteria Evaluation',
      content: '5/6 criteria fully met. 1 criterion (pre-operative cardiac evaluation) has insufficient documentation. However, the criterion states documentation must be submitted within 90 days; a note references completion of pre-op evaluation without explicit cardiac clearance letter.',
    },
    {
      step: 'Clinical Judgment',
      content: 'Patient profile: 73F, BMI 28.4, failed PT (6 months), failed pharmacotherapy (GI intolerance), failed 3 corticosteroid injections. This is a textbook indication for TKA per standard clinical guidelines and payer policy.',
    },
    {
      step: 'Recommendation Formation',
      content: 'Confidence of 0.91 reflects high certainty on primary criteria (4 criteria >0.93 confidence) offset by insufficient cardiac clearance documentation (0.61). Recommend approval with note to obtain cardiac clearance confirmation.',
    },
  ],
  caveats: [
    'Pre-operative cardiac evaluation documentation should be verified before scheduling',
    'Surgical site infection risk protocols should be confirmed given patient age',
  ],
  policy_refs: [
    'TKA Medical Necessity Criteria §4.2.1-4.2.5',
    'Pre-surgical Clearance Requirements §4.3.1',
    'Conservative Treatment Documentation Standards §3.1',
  ],
}

export function RationaleViewer() {
  const [expandedStep, setExpandedStep] = useState<number | null>(0)

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Brain className="w-4.5 h-4.5 text-violet-400" />
            <h3 className="text-sm font-semibold text-[var(--text-1)]">AI Clinical Rationale</h3>
          </div>
          <p className="text-xs text-[var(--text-3)] mt-0.5">
            Generated by {RATIONALE.model} ({RATIONALE.tier} tier)
          </p>
        </div>
        <div className="text-right">
          <p className="text-xs text-[var(--text-3)] mb-1">Overall Confidence</p>
          <ConfidenceBar value={RATIONALE.confidence} variant="ring" />
        </div>
      </div>

      {/* Summary */}
      <div className="p-4 rounded-xl bg-[var(--elevated)] border border-[var(--border)]">
        <div className="flex items-center gap-2 mb-2">
          <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
          <span className="text-xs font-semibold text-[var(--text-2)] uppercase tracking-wide">Summary</span>
        </div>
        <p className="text-sm text-[var(--text-1)] leading-relaxed">{RATIONALE.summary}</p>
      </div>

      {/* Reasoning steps */}
      <div>
        <p className="section-label mb-3">Reasoning Chain ({RATIONALE.reasoning_steps.length} steps)</p>
        <div className="space-y-2">
          {RATIONALE.reasoning_steps.map((step, i) => (
            <div key={i} className="rounded-xl border border-[var(--border)] overflow-hidden">
              <button
                onClick={() => setExpandedStep(expandedStep === i ? null : i)}
                className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-[var(--elevated)] transition-colors"
              >
                <span className="w-6 h-6 rounded-full bg-brand-500/15 text-brand-400 text-xs flex items-center justify-center font-bold flex-shrink-0">
                  {i + 1}
                </span>
                <span className="flex-1 text-sm font-medium text-[var(--text-1)]">{step.step}</span>
                {expandedStep === i
                  ? <ChevronUp className="w-4 h-4 text-[var(--text-3)]" />
                  : <ChevronDown className="w-4 h-4 text-[var(--text-3)]" />
                }
              </button>
              <AnimatePresence>
                {expandedStep === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="px-4 pb-4 pt-1 border-t border-[var(--border)]">
                      <p className="text-sm text-[var(--text-2)] leading-relaxed">{step.content}</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>

      {/* Caveats */}
      {RATIONALE.caveats.length > 0 && (
        <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/15">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
            <span className="text-xs font-semibold text-amber-400 uppercase tracking-wide">Caveats</span>
          </div>
          <ul className="space-y-1">
            {RATIONALE.caveats.map((c, i) => (
              <li key={i} className="text-sm text-[var(--text-2)] flex items-start gap-2">
                <span className="text-amber-400 mt-1">•</span>
                {c}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Policy references */}
      <div>
        <p className="section-label mb-2">Policy References</p>
        <div className="space-y-1.5">
          {RATIONALE.policy_refs.map((ref, i) => (
            <div key={i} className="flex items-center gap-2 text-sm text-[var(--text-2)]">
              <BookOpen className="w-3.5 h-3.5 text-brand-400 flex-shrink-0" />
              {ref}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}